import type { TechCategory, TechItem } from "@/types";

export const techCategories: TechCategory[] = [
  { id: "all", label: "All" },
  { id: "frontend", label: "Front-End" },
  { id: "backend", label: "Back-End" },
  { id: "database", label: "Database" },
  { id: "devops", label: "DevOps" },
  { id: "mobile", label: "Mobile" },
  { id: "ai", label: "AI & ML" },
];

export const techStack: TechItem[] = [
  { name: "JavaScript", category: "frontend" },
  { name: "TypeScript", category: "frontend" },
  { name: "React.js", category: "frontend" },
  { name: "Next.js", category: "frontend" },
  { name: "Vue.js", category: "frontend" },
  { name: "Nuxt.js", category: "frontend" },
  { name: "Angular", category: "frontend" },
  { name: "Tailwind CSS", category: "frontend" },
  { name: "Node.js", category: "backend" },
  { name: "Nest.js", category: "backend" },
  { name: "Fastify", category: "backend" },
  { name: "Python", category: "backend" },
  { name: "FastAPI", category: "backend" },
  { name: "Django", category: "backend" },
  { name: "Java", category: "backend" },
  { name: "Spring Boot", category: "backend" },
  { name: "PHP", category: "backend" },
  { name: "Laravel", category: "backend" },
  { name: "MongoDB", category: "database" },
  { name: "PostgreSQL", category: "database" },
  { name: "MySQL", category: "database" },
  { name: "Redis", category: "database" },
  { name: "Firebase", category: "database" },
  { name: "AWS", category: "devops" },
  { name: "Microsoft Azure", category: "devops" },
  { name: "GCP", category: "devops" },
  { name: "Docker", category: "devops" },
  { name: "Kubernetes", category: "devops" },
  { name: "Terraform", category: "devops" },
  { name: "React Native", category: "mobile" },
  { name: "Flutter", category: "mobile" },
  { name: "Android", category: "mobile" },
  { name: "iOS", category: "mobile" },
  { name: "OpenAI", category: "ai" },
  { name: "LangChain", category: "ai" },
  { name: "TensorFlow", category: "ai" },
  { name: "PyTorch", category: "ai" },
];
