import type { TechCategory, TechItem } from "@/types";

export const techCategories: TechCategory[] = [
  { id: "all", label: "All" },
  { id: "frontend", label: "Front-End" },
  { id: "backend", label: "Back-End" },
  { id: "database", label: "Database" },
  { id: "devops", label: "DevOps" },
  { id: "mobile", label: "Mobile" },
  { id: "ai", label: "AI & ML" },
];

export const techStack: TechItem[] = [
  { name: "JavaScript", category: "frontend", icon: "DiJavascript" },
  { name: "TypeScript", category: "frontend", icon: "BsTypescript" },
  { name: "React.js", category: "frontend", icon: "FaReact" },
  { name: "Next.js", category: "frontend", icon: "RiNextjsLine" },
  { name: "Vue.js", category: "frontend", icon: "FaVuejs" },
  { name: "Nuxt.js", category: "frontend", icon: "SiNuxt" },
  { name: "Angular", category: "frontend", icon: "RiAngularjsLine" },
  { name: "Tailwind CSS", category: "frontend", icon: "RiTailwindCssFill" },
  { name: "Node.js", category: "backend", icon: "FaNodeJs" },
  { name: "Nest.js", category: "backend", icon: "SiNestjs" },
  { name: "Fastify", category: "backend", icon: "SiFastify" },
  { name: "Python", category: "backend", icon: "FaPython" },
  { name: "FastAPI", category: "backend", icon: "SiFastapi" },
  { name: "Django", category: "backend", icon: "SiDjango" },
  { name: "Java", category: "backend", icon: "FaJava" },
  { name: "Spring Boot", category: "backend", icon: "BiLogoSpringBoot" },
  { name: "PHP", category: "backend", icon: "FaPhp" },
  { name: "Laravel", category: "backend", icon: "FaLaravel" },
  { name: "MongoDB", category: "database", icon: "SiMongodb" },
  { name: "PostgreSQL", category: "database", icon: "SiPostgresql" },
  { name: "MySQL", category: "database", icon: "GrMysql" },
  { name: "Redis", category: "database", icon: "DiRedis" },
  { name: "Firebase", category: "database", icon: "IoLogoFirebase" },
  { name: "AWS", category: "devops", icon: "FaAws" },
  { name: "Microsoft Azure", category: "devops", icon: "VscAzure" },
  { name: "GCP", category: "devops", icon: "SiGooglecloud" },
  { name: "Docker", category: "devops", icon: "FaDocker" },
  { name: "Kubernetes", category: "devops", icon: "SiKubernetes" },
  { name: "Terraform", category: "devops", icon: "SiTerraform" },
  { name: "React Native", category: "mobile", icon: "TbBrandReactNative" },
  { name: "Flutter", category: "mobile", icon: "SiFlutter" },
  { name: "Android", category: "mobile", icon: "SiAndroid" },
  { name: "iOS", category: "mobile", icon: "SiIos" },
  { name: "OpenAI", category: "ai", icon: "SiOpenai" },
  { name: "LangChain", category: "ai", icon: "SiLangchain" },
  { name: "TensorFlow", category: "ai", icon: "SiTensorflow" },
  { name: "PyTorch", category: "ai", icon: "SiPytorch" },
];
